# Generated by Django 4.1.7 on 2023-03-11 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorite',
            name='favorite_type',
            field=models.CharField(choices=[('Programma', 'Programma'), ('Maqola', 'Maqola')], default=1, max_length=50),
            preserve_default=False,
        ),
    ]
